// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp7b+O2lv8qhG6BmfZKtvxM4sVi4Uk8GS8SJxsnxW0ns760eGRzKpEqSSVxB/7uC5KSbD0yTuem7WKx",
	"/yUWH4fn8Tu/c8gvTsDjhDNgSjqjL06CBY5BgTD/nVN1AwmXVHGxmZJrrNb6ZwIyEDRRlDNn5Nwx+msK",
	"iBJgioYUBAq5QGoNaEUVEsV8x3XgCcdJBM7ISQQnaaBX8HCSSMd1qF4r0Tu4DsOxHrQqb++4joBfUyqA",
	"OCMlUnAdGawhxlZwpUDoNf77I/Z+872TT2+zP7xPX3x32Nnmv3//H985rqM2id5DKkHZytlut3p1mXAm",
	"wZx9HAnAZDN5otKqJuBMAVP6T5wkEQ2wFr/9WWotfNmdTetHYRo5o7L+0CNVa0QJelM5/BuE7V4I7GZa",
	"GVJhFmgB/WB4tFoP194RnAy9o0EAHvTWxx50VsPj3jrsnxxrlUmFVSqdUd8/cR1FldHyDUieigDqG2Sn",
	"H1/cTMZnPy0m/5jOb+fOdl+j3wkInZHzt/bOQ9r2q2xPhODCKq3sDJnWUKa2reu8w+QGfk1Bqm9U4nsK",
	"EUFvZAJBKxXRGxSnUiHGFVoCgjhRm7LCjk56fRL2wOsvhz2v3z1Zeks/HHjLY9Ib+BB0hgMoKczfKWzK",
	"HnBECRJWYrQXDoXOprMfxxfTs8X45vzucjK7fQWtvcME5Uraus57LpaUEGDfqLE7CQIRDtJoaY0fACUg",
	"Yiol5QwpjnAQgJRIralEIvORshKPcX8AYT/0BsFR3xv0cOAFnXDoBSfQH3ZC0j0ahiUl9nZKHNvVw+IU",
	"hequJzeX0/l8ejVbnE1m08nZK+hup6yt60yZBgEczUE8gLBzvk2HY4ZSBk8JBAoIAr0S4kGQCgEEPa5p",
	"BCgRXB+UspVBu8xnynrswvEJ/Xz82TtZdY69kyNYeavBZ99b9eixP/i8Hnb8z3t6HJSd0R4GSXMaK8S+",
	"H95Obmbji1fQYbGT1RvKBrrOjKv3PGXkVfCvjnuFjxpcKmvuZDkYhqvByhuS44E37C+JR7qrI4/44eCo",
	"u4Le8dGq5IH9BtzTa4fmAIXaZle3i/dXd7PX8L0ZV8jqZ+s6dwynas0F/Q2+VV8/GvDRy+hcaiegQIBJ",
	"rTiSCAvrZzoHviyQh0G3R6BLvB4edL1+9xh7eOgPPHxEun2fLP1Bn5TU2NkL5LIgRfItdHk3G9/dfpjM",
	"bqen49tXieaSErfFeiYBF+FcnmJ+RnnuRiGPIv6og/Lm/Sk6OvaP0LXgywhidGb0bJAJfbi9vUbj66m8",
	"Z5gRNJ5ce52TnvV8dJMTAaSzDg0zDbTuNZYlgicgFLU0IbddVaoPaYyZp5MhXkaA4CmJMLN6zNfUBjSW",
	"y3CFBYB4aLDEhLrdbseZXpQIK7Rm3xdeStzo7thl4GMBVGV6YbINuYixckZOKqgnIASzWJO4uSPW9Knt",
	"ZT+igBNAb2OsgjXIDHsz69sR3+/LaBJ8IQBlqtfdbUyZghUYrMu8vrrxfM2FctG6bE+ZxjEWm5K9kF6z",
	"qqCXMIrd6e0PVREucbCmDPa8yWyn1ZBtx9LYGX2sUxO3FqLuHgC6Vf7nNmRo13k/nl5MzhbXN5PTq9nZ",
	"9HZ6NXPcXfoxe/w4nl6M311MnE+lw9fleaknbPfJ/kf7tfCO3Fifiml8+RkCQ55KOcdUBqV4xQldPICQ",
	"1KJwWdE/2g+5VcvpyyIRegutVctFDx0cJWvc+b51z6ZxnCpjGBwqEBqx9/Bip458jgaRXbny8FEXJX/X",
	"1cmnv9u/v2vyDbMqLBSNG1zklsYgFY4T9LgGlseETYKPWFqRgKC3GhR7vd5JKUScrt8dev7Q6/i3HX/U",
	"80e+//O+sQhW4JmdtVkwuWLRJq/BaoISKpMIbxa2iquhjgThhYICI9EGZWORHvtM3YgCzkK6SkWjTq8L",
	"ToHGtpCM8dMFsJUuVYc914kpy//tNAibNNa0BYHQnxG1CrXaGGnxvEI8CrL9pVKobisy1ibUq989f6iN",
	"flk9e9AsGtMP5eWSx8/1hBIkv3yqnbJ1nZSSb28ZtNCtzkahSXw6UaYqSZXHWbRBmJF7Rp+LPHS7BjQ9",
	"QwFmOjtyszOOok2e2oCgB4rv2a8piM0OlZElXGaRf0M0NOk1EfyBEiCuETFj4ytgILACiTC6u5uete7Z",
	"PXtvyIe0dKLb3cWgFoWzB31ezmTViev+8FUn/t29joO+kSbk27ElwlKhmBOr1RcgTHfUH/wLCFNJDfuI",
	"XgGfzOlracJ1njwMiVdQ5l0DSeolGyN8sfPLBSVbvWoSpQJHDRGud6ZslUZYVL/ukbQVVTyRXowZXoFo",
	"kSBuUd6ujN5Wc9oFta2Ucl5j8KQWCV7BQvFfoCG33eqfTZwJUILCQ1636plIz9RpT4BMI6UddKIJJbI6",
	"R5QRzYEhKzWoZV3G8Hpm1Z9h858PP8c///bzP/6LXn2ePF5+8P+9KaVlu9WFHQuBDbmqpILcYFrAS7wp",
	"iK+N1Fx6ZKihEdGEtxWPKoh/H4rtGJmDtUA118vld2vqP8hM5hkaV8jmfrlhjIUbsiGD4LlyRPNZ8YCj",
	"hYSAM5KpNsRppJzR0K+WW9c8iqx97TSd6rKZ6G1MGY3TGHV8+X3FwsMmSp2Nd0Ydv4lf7zJtJo7Tcqry",
	"nFEBQdEspTnYJLyFNCCgn8aXFyikEUhEzFCdCJRxyntmcrXgXGVlMiborYZvmS5Jti6F2lF0cb6fkdvN",
	"jhpwFtCIYtVIHG9K39ES1viBGopeoy5le+lY3CwSHtGggawucfALD8NGY/b8ehfRjEZLUI8ALItzuWfT",
	"ytF7X7dikxFj/LTI1i1L49ZqlifjPCyNlzqthoU4ugJOlzFVKMQ0SkUVPXpfE6rBs7a1UNs2BJ+J+arZ",
	"zk1oZTWILscfNXA02WkpMAsq7htjymoe/M4MrKy1c7ZsTj2j1QRORfScwAUW3N1cVDdYK5XIUVtnkVb2",
	"ayvgcVsBjtskiA3BaK2ocg5Q4wrUaXEOg9ozxft8w4K8eG8CtSaN6+SykBsWHGQlWbVmspGegHQmjxO1",
	"R0WqWvo9bKQGBoVkQBYBj2OqGqSz5SOy39H8wxipNVY7viRT07oLU8NJzWI1YFoGnW6PQNgfDJvkiEFK",
	"vIKDvadsHMJLniqjKtvNUZlJWvfsdpPQwNDjgDOFKZNZj4FkLTPD/Iw19BzQDGByc3N1U5V5HOkcYjtO",
	"MjtX6ayNPZ9i3fpZTnNRcxfScOGh68nsbDo7H6Epo4riyH5yNQkwI9dY7tr1G1Bm0vyn2enkbITOTi/t",
	"eJT3kLSpsDKWmRuZT43dzKzpbHF9c3V+M5nPR+iChhBsgghQsMZsBRKFgsd2vgC0BJ1NTbvX2NOzWhoh",
	"EwEa7zRDxqlau4iBeuTiF1cXHzLr6RTZKWvoZMd0XMfKbvouhTiO65jly02XYuRBkNma9mDI8241DrQn",
	"13qy2pe1ys6pukokurR0FY2vp3lltGs+2/jO055WxjlVHhH0Adg9O8UKR3w1VRBPMydBUaFRy4NjYMrU",
	"Un/7G8rLcKn/99APP+yjDQX5ww8jdJrtBXvMSGr8LWGlTjyZa1O2umcINcli6AWBkGqn0nUaGiMJujhU",
	"gP6p0dNS9n/mdz8o4VEk9XL5kYGUN8VM/2DZAcid61k7RzQAJo3bZ3fe4wQHa0Ddlu9kOaCA9MfHxxY2",
	"n1tcrNrZXNm+mJ5OZvOJ1235rbWKo71mptNsN8d1ih7Yriu1dR2eAMMJdUZOr+W3+rYxsTZ43K7VOKMv",
	"zgpUExky9YWpjBO8osx0niIqVQOjLzEkDUXzNEm4UFKriREsSL6GJlapuW0zxYrh2Rmj0XnDDJgSZ+To",
	"AqniKOYgu5cNH//V4uhqqT0JiI3+fOBeAZD1LHiodSDggfJUFl3qrB7RG5v6ZPfiYa+C2L9KqUXyl4Ns",
	"y1Q7OgwEqFQwlIDIS7Wp7WoUjRAXZZzGjO/4/vPyafpnZJT0NyiJWNCiTmO7PbYCms/+10nm9lPlJUbX",
	"919wn/ayi6d6Jd1wCTUv8lVhMh0cfStH0/KFvO295w5mSufwlPKdl57UOzypdO09eIlkTXfj5obNXmVk",
	"gVOOTx06unTjsiHOT01PWUc5g8dDTdu9wE4lCG/XhpueSfRAsYmiN5S8QdWWnA5LSiBOuAIWbKwHK9vf",
	"o/L5Dt0jjaKiTYc4gyawsIcol/0HwOIqaybWD/JcG/OeXaZSZVeT6Gw29zqdbg9FeAlR1lZGbyP+CCLA",
	"EpDBY5bGIGhgXw2tN8kamGEH0xDxmCr1fDuSIdONfMl7q0p4U+J85U3V73xQ9ckWECDVO042f0wE5++2",
	"9l+FbWvw0fkjN/9qgZZfu5QY8A5KXkWmr7zqKF89LjnZIC6Q+dXmU8gfevxJQNX3Tw7PKL+8ez14s6Fe",
	"Kz7NqPbhSx0LgBE0VSln5nfZ2K2rNoDK+GNnHsCfppPvhrSbnmk2ZNH+wX6CPV6Tu/5J3tE/PKN4kvR6",
	"jmFt0OAY7mGCqwlp9PUrS7TcIKpkgcplBzgH9adY3//LQDDMzfV/3I3OQTX6UJI2+lAS4eCbIOPOXNb9",
	"UU7zvyJj/3XOam9C/z9j/9XBZJ28KVnrYWaadXTbI2njhLZ3nYxP2/8JAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
