// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS      ErrorType = "ALREADY_EXISTS"
	FAILEDPRECONDITION ErrorType = "FAILED_PRECONDITION"
	INTERNAL           ErrorType = "INTERNAL"
	INVALIDARGUMENT    ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           ErrorType = "NOT_FOUND"
	PERMISSIONDENIED   ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED    ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE        ErrorType = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case FAILEDPRECONDITION:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for GitRepositoryStatusSyncState.
const (
	ERROR      GitRepositoryStatusSyncState = "ERROR"
	INPROGRESS GitRepositoryStatusSyncState = "IN_PROGRESS"
	PENDING    GitRepositoryStatusSyncState = "PENDING"
	SYNCED     GitRepositoryStatusSyncState = "SYNCED"
)

// Valid indicates whether the value is a known member of the GitRepositoryStatusSyncState enum.
func (e GitRepositoryStatusSyncState) Valid() bool {
	switch e {
	case ERROR:
		return true
	case INPROGRESS:
		return true
	case PENDING:
		return true
	case SYNCED:
		return true
	default:
		return false
	}
}

// Error Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type Error struct {
	// Detail Human-readable explanation specific to this occurrence of the error.
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this specific error occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code (matches the response status)
	Status int32 `json:"status"`

	// Title Short, human-readable summary of the error type.
	Title string `json:"title"`

	// Type Machine-readable error code.
	Type ErrorType `json:"type"`
}

// ErrorType Machine-readable error code.
type ErrorType string

// GitRepository defines model for GitRepository.
type GitRepository struct {
	// ApiVersion Version of the GitRepository schema (e.g., v1alpha1).
	// Immutable after creation.
	ApiVersion string `json:"api_version"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// DisplayName User-friendly display name for the git repository configuration.
	DisplayName string `json:"display_name"`

	// Path Resource path in the format: git-repositories/{gitRepositoryId}
	Path *string `json:"path,omitempty"`

	// Spec Specification for a git repository connection.
	Spec GitRepositorySpec `json:"spec"`

	// Status Sync status for a git repository.
	Status *GitRepositoryStatus `json:"status,omitempty"`

	// Uid Unique identifier for the git repository. This field is output-only and
	// immutable after creation. The ID can be optionally specified via
	// query parameter on creation; if not provided, the server generates a UUID.
	//
	// Follows AEP-122 resource ID conventions.
	Uid *string `json:"uid,omitempty"`

	// UpdateTime Timestamp when the resource was last modified (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// GitRepositoryList defines model for GitRepositoryList.
type GitRepositoryList struct {
	// NextPageToken Token for retrieving the next page of results.
	// Empty string indicates this is the last page.
	NextPageToken string `json:"next_page_token"`

	// Results Array of git repository resources.
	// May be empty if no results match the query.
	Results []GitRepository `json:"results"`
}

// GitRepositorySpec Specification for a git repository connection.
type GitRepositorySpec struct {
	// IntervalSeconds Polling interval in seconds (minimum 10s).
	IntervalSeconds *int32 `json:"interval_seconds,omitempty"`

	// Path Directory within the repo. Only YAML files directly at this
	// path root are read (not subdirectories).
	Path *string `json:"path,omitempty"`

	// Reconciliation Reconciliation behavior configuration.
	Reconciliation *struct {
		RetryPolicy *struct {
			// BackoffSeconds Backoff between retries in seconds.
			BackoffSeconds *int32 `json:"backoff_seconds,omitempty"`

			// MaxRetries Maximum number of retries on submit failure.
			MaxRetries *int32 `json:"max_retries,omitempty"`
		} `json:"retry_policy,omitempty"`
	} `json:"reconciliation,omitempty"`

	// Ref Git reference to watch.
	Ref *struct {
		// Branch Branch to watch.
		Branch *string `json:"branch,omitempty"`
	} `json:"ref,omitempty"`

	// Url Git repository URL.
	Url string `json:"url"`
}

// GitRepositoryStatus Sync status for a git repository.
type GitRepositoryStatus struct {
	// LastSyncTime Timestamp of the last sync attempt (RFC 3339).
	LastSyncTime *time.Time `json:"last_sync_time,omitempty"`

	// LastSyncedCommit The Git commit SHA that was last successfully synced.
	LastSyncedCommit *string `json:"last_synced_commit,omitempty"`

	// Message Human-readable message about the current status.
	// Typically contains error details when sync_state is ERROR.
	Message *string `json:"message,omitempty"`

	// SyncState Current sync state.
	// - PENDING: Initial state, no sync has occurred yet.
	// - SYNCED: DCM state matches Git at lastSyncedCommit.
	// - IN_PROGRESS: Lifecycle changes from Git are being applied.
	// - ERROR: Sync failed (auth, network, parse errors).
	SyncState *GitRepositoryStatusSyncState `json:"sync_state,omitempty"`
}

// GitRepositoryStatusSyncState Current sync state.
// - PENDING: Initial state, no sync has occurred yet.
// - SYNCED: DCM state matches Git at lastSyncedCommit.
// - IN_PROGRESS: Lifecycle changes from Git are being applied.
// - ERROR: Sync failed (auth, network, parse errors).
type GitRepositoryStatusSyncState string

// GitRepositoryIdPath defines model for GitRepositoryIdPath.
type GitRepositoryIdPath = string

// AlreadyExists Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type AlreadyExists = Error

// BadRequest Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type BadRequest = Error

// Forbidden Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type Forbidden = Error

// InternalServerError Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type InternalServerError = Error

// NotFound Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type NotFound = Error

// Unauthorized Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type Unauthorized = Error

// ListGitRepositoriesParams defines parameters for ListGitRepositories.
type ListGitRepositoriesParams struct {
	// PageToken Token for retrieving the next page of results.
	// Obtained from the next_page_token field of a previous response.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of items to return per page.
	// If not specified, defaults to 100.
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateGitRepositoryParams defines parameters for CreateGitRepository.
type CreateGitRepositoryParams struct {
	// Id Optional user-specified ID for the git repository.
	// Must follow DNS-1123 label format (lowercase alphanumeric with hyphens).
	// If omitted, the server generates an ID.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateGitRepositoryJSONRequestBody defines body for CreateGitRepository for application/json ContentType.
type CreateGitRepositoryJSONRequestBody = GitRepository

// UpdateGitRepositoryJSONRequestBody defines body for UpdateGitRepository for application/json ContentType.
type UpdateGitRepositoryJSONRequestBody = GitRepository
