apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dcm.fullname" . }}-db
  labels:
    {{- include "dcm.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_PASS: {{ .Values.postgres.password | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
