// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	. "github.com/dcm-project/control-plane/api/gitops/v1alpha1"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List git repositories
	// (GET /git-repositories)
	ListGitRepositories(w http.ResponseWriter, r *http.Request, params ListGitRepositoriesParams)
	// Create a git repository
	// (POST /git-repositories)
	CreateGitRepository(w http.ResponseWriter, r *http.Request, params CreateGitRepositoryParams)
	// Delete a git repository
	// (DELETE /git-repositories/{gitRepositoryId})
	DeleteGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath)
	// Get a git repository
	// (GET /git-repositories/{gitRepositoryId})
	GetGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath)
	// Update a git repository
	// (PUT /git-repositories/{gitRepositoryId})
	UpdateGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List git repositories
// (GET /git-repositories)
func (_ Unimplemented) ListGitRepositories(w http.ResponseWriter, r *http.Request, params ListGitRepositoriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a git repository
// (POST /git-repositories)
func (_ Unimplemented) CreateGitRepository(w http.ResponseWriter, r *http.Request, params CreateGitRepositoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a git repository
// (DELETE /git-repositories/{gitRepositoryId})
func (_ Unimplemented) DeleteGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a git repository
// (GET /git-repositories/{gitRepositoryId})
func (_ Unimplemented) GetGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a git repository
// (PUT /git-repositories/{gitRepositoryId})
func (_ Unimplemented) UpdateGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListGitRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListGitRepositories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGitRepositoriesParams

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGitRepositories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGitRepository operation middleware
func (siw *ServerInterfaceWrapper) CreateGitRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateGitRepositoryParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGitRepository(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGitRepository operation middleware
func (siw *ServerInterfaceWrapper) DeleteGitRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gitRepositoryId" -------------
	var gitRepositoryId GitRepositoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "gitRepositoryId", chi.URLParam(r, "gitRepositoryId"), &gitRepositoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gitRepositoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGitRepository(w, r, gitRepositoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGitRepository operation middleware
func (siw *ServerInterfaceWrapper) GetGitRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gitRepositoryId" -------------
	var gitRepositoryId GitRepositoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "gitRepositoryId", chi.URLParam(r, "gitRepositoryId"), &gitRepositoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gitRepositoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGitRepository(w, r, gitRepositoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGitRepository operation middleware
func (siw *ServerInterfaceWrapper) UpdateGitRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gitRepositoryId" -------------
	var gitRepositoryId GitRepositoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "gitRepositoryId", chi.URLParam(r, "gitRepositoryId"), &gitRepositoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gitRepositoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGitRepository(w, r, gitRepositoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/git-repositories", wrapper.ListGitRepositories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/git-repositories", wrapper.CreateGitRepository)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/git-repositories/{gitRepositoryId}", wrapper.DeleteGitRepository)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/git-repositories/{gitRepositoryId}", wrapper.GetGitRepository)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/git-repositories/{gitRepositoryId}", wrapper.UpdateGitRepository)
	})

	return r
}

type AlreadyExistsJSONResponse Error

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListGitRepositoriesRequestObject struct {
	Params ListGitRepositoriesParams
}

type ListGitRepositoriesResponseObject interface {
	VisitListGitRepositoriesResponse(w http.ResponseWriter) error
}

type ListGitRepositories200JSONResponse GitRepositoryList

func (response ListGitRepositories200JSONResponse) VisitListGitRepositoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGitRepositories400JSONResponse struct{ BadRequestJSONResponse }

func (response ListGitRepositories400JSONResponse) VisitListGitRepositoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListGitRepositories401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListGitRepositories401JSONResponse) VisitListGitRepositoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListGitRepositories403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListGitRepositories403JSONResponse) VisitListGitRepositoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListGitRepositories500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListGitRepositories500JSONResponse) VisitListGitRepositoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGitRepositoryRequestObject struct {
	Params CreateGitRepositoryParams
	Body   *CreateGitRepositoryJSONRequestBody
}

type CreateGitRepositoryResponseObject interface {
	VisitCreateGitRepositoryResponse(w http.ResponseWriter) error
}

type CreateGitRepository201JSONResponse GitRepository

func (response CreateGitRepository201JSONResponse) VisitCreateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGitRepository400JSONResponse Error

func (response CreateGitRepository400JSONResponse) VisitCreateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGitRepository401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGitRepository401JSONResponse) VisitCreateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGitRepository403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateGitRepository403JSONResponse) VisitCreateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGitRepository409JSONResponse struct{ AlreadyExistsJSONResponse }

func (response CreateGitRepository409JSONResponse) VisitCreateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGitRepository500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateGitRepository500JSONResponse) VisitCreateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGitRepositoryRequestObject struct {
	GitRepositoryId GitRepositoryIdPath `json:"gitRepositoryId"`
}

type DeleteGitRepositoryResponseObject interface {
	VisitDeleteGitRepositoryResponse(w http.ResponseWriter) error
}

type DeleteGitRepository204Response struct {
}

func (response DeleteGitRepository204Response) VisitDeleteGitRepositoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteGitRepository401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteGitRepository401JSONResponse) VisitDeleteGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGitRepository403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteGitRepository403JSONResponse) VisitDeleteGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGitRepository404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteGitRepository404JSONResponse) VisitDeleteGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGitRepository500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteGitRepository500JSONResponse) VisitDeleteGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetGitRepositoryRequestObject struct {
	GitRepositoryId GitRepositoryIdPath `json:"gitRepositoryId"`
}

type GetGitRepositoryResponseObject interface {
	VisitGetGitRepositoryResponse(w http.ResponseWriter) error
}

type GetGitRepository200JSONResponse GitRepository

func (response GetGitRepository200JSONResponse) VisitGetGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGitRepository401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGitRepository401JSONResponse) VisitGetGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGitRepository403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetGitRepository403JSONResponse) VisitGetGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGitRepository404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGitRepository404JSONResponse) VisitGetGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGitRepository500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetGitRepository500JSONResponse) VisitGetGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGitRepositoryRequestObject struct {
	GitRepositoryId GitRepositoryIdPath `json:"gitRepositoryId"`
	Body            *UpdateGitRepositoryJSONRequestBody
}

type UpdateGitRepositoryResponseObject interface {
	VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error
}

type UpdateGitRepository200JSONResponse GitRepository

func (response UpdateGitRepository200JSONResponse) VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGitRepository400JSONResponse Error

func (response UpdateGitRepository400JSONResponse) VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGitRepository401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateGitRepository401JSONResponse) VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGitRepository403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateGitRepository403JSONResponse) VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGitRepository404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateGitRepository404JSONResponse) VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGitRepository500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateGitRepository500JSONResponse) VisitUpdateGitRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List git repositories
	// (GET /git-repositories)
	ListGitRepositories(ctx context.Context, request ListGitRepositoriesRequestObject) (ListGitRepositoriesResponseObject, error)
	// Create a git repository
	// (POST /git-repositories)
	CreateGitRepository(ctx context.Context, request CreateGitRepositoryRequestObject) (CreateGitRepositoryResponseObject, error)
	// Delete a git repository
	// (DELETE /git-repositories/{gitRepositoryId})
	DeleteGitRepository(ctx context.Context, request DeleteGitRepositoryRequestObject) (DeleteGitRepositoryResponseObject, error)
	// Get a git repository
	// (GET /git-repositories/{gitRepositoryId})
	GetGitRepository(ctx context.Context, request GetGitRepositoryRequestObject) (GetGitRepositoryResponseObject, error)
	// Update a git repository
	// (PUT /git-repositories/{gitRepositoryId})
	UpdateGitRepository(ctx context.Context, request UpdateGitRepositoryRequestObject) (UpdateGitRepositoryResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListGitRepositories operation middleware
func (sh *strictHandler) ListGitRepositories(w http.ResponseWriter, r *http.Request, params ListGitRepositoriesParams) {
	var request ListGitRepositoriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGitRepositories(ctx, request.(ListGitRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGitRepositories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGitRepositoriesResponseObject); ok {
		if err := validResponse.VisitListGitRepositoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGitRepository operation middleware
func (sh *strictHandler) CreateGitRepository(w http.ResponseWriter, r *http.Request, params CreateGitRepositoryParams) {
	var request CreateGitRepositoryRequestObject

	request.Params = params

	var body CreateGitRepositoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGitRepository(ctx, request.(CreateGitRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGitRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGitRepositoryResponseObject); ok {
		if err := validResponse.VisitCreateGitRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteGitRepository operation middleware
func (sh *strictHandler) DeleteGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath) {
	var request DeleteGitRepositoryRequestObject

	request.GitRepositoryId = gitRepositoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteGitRepository(ctx, request.(DeleteGitRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteGitRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteGitRepositoryResponseObject); ok {
		if err := validResponse.VisitDeleteGitRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGitRepository operation middleware
func (sh *strictHandler) GetGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath) {
	var request GetGitRepositoryRequestObject

	request.GitRepositoryId = gitRepositoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGitRepository(ctx, request.(GetGitRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGitRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGitRepositoryResponseObject); ok {
		if err := validResponse.VisitGetGitRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateGitRepository operation middleware
func (sh *strictHandler) UpdateGitRepository(w http.ResponseWriter, r *http.Request, gitRepositoryId GitRepositoryIdPath) {
	var request UpdateGitRepositoryRequestObject

	request.GitRepositoryId = gitRepositoryId

	var body UpdateGitRepositoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateGitRepository(ctx, request.(UpdateGitRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateGitRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateGitRepositoryResponseObject); ok {
		if err := validResponse.VisitUpdateGitRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

